<MyGrid>
    GridLayout:
        size: root.width - 200, root.height - 200
        cols:1
        pos: 100, 100

        GridLayout:
            cols: 2
            Label:
                text: "Name"
            TextInput:
                multiline: False
            Label:
                text: "Email"
            TextInput:
                multiline: False

        Button:
            text: "Submit"
